<!DOCTYPE html><!-- "' --></textarea></script></style></pre></xmp></a></audio></button></canvas></datalist></details></dialog></iframe></listing></meter></noembed></noframes></noscript></optgroup></option></progress></rp></select></table></template></title></video>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<title>Chyba serveru</title>

<section class="error">
	<div class="error__wrapper wrapper">
		<div id=nette-error>
			<div>
				<h1>Chyba serveru</h1>
				<p>
					Omlouváme se! Server zaznamenal interní chybu <br>
					a nemohl dokončit váš požadavek. Zkuste to prosím za chvíli.
				</p>

				<p><small>chyba 500</small></p>
			</div>
		</div>
	</div>
</section>

<script>
	document.body.insertBefore(document.getElementById('nette-error'), document.body.firstChild);
</script>
