<?php

declare(strict_types=1);

header('HTTP/1.1 503 Service Unavailable');
header('Retry-After: 300'); // 5 minutes in seconds

?>
<!DOCTYPE html>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<meta name="generator" content="Nette Framework">


<title>Stránka je dočasně mimo provoz</title>

<div class="errorPage">
	<div class="errorPage__wrapper wrapper">
		<h1>Omlouváme se</h1>

		<p class="errorPage__copy">
			Stránka je dočasně mimo provoz kvůli údržbě. Zkuste to, prosím, za okamžik.
		</p>
	</div>
</div>

